### ISSUE TITLE
Helping a novice...

### ISSUE THREAD

**Issue by Bio-data-tricks** [clhenrick/portfolio#47]
Hi Clhenrick, 

I would like to have a personal page in the same way as your portfolio. But I'm really not a specialist for this kind of thing...
Is it possible to host your portfolio on Github like the "Feeling Responsive" template ? 
Your page is exactly what I am looking for, but it seems to be more complicated than the "Feeling Responsive" to make it work. 
Can you please help me ? 

Nicolas

**Comment by clhenrick** [comment]
Hi Nicolas, I'm sorry but I don't have the resources to help you with this. You absolutely may host custom Jekyll templates on Github pages, I would check both the Github Pages and Jekyll documentation for how to do it. 

If you do fork my code please make sure to remove anything related to my work and writings.
